POST http://localhost:8080/event
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImV4cCI6MTc2NTQ0ODUxNywidXNlcklkIjoxfQ.hzZi2kFnseZLSvtm6O1ZoV1Y7FeLEylcGyDn2Pj1So4

{
    "name": "event 17",
    "description": "event description",
    "location": "event location",
    "dateTime": "2024-07-01T10:00:00Z"
}