DELETE http://localhost:8080/event/3/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImV4cCI6MTc2NTQ0ODUxNywidXNlcklkIjoxfQ.hzZi2kFnseZLSvtm6O1ZoV1Y7FeLEylcGyDn2Pj1So4
