DELETE http://localhost:8080/event/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQGdtYWlsLmNvbSIsImV4cCI6MTc2NTM4MTk5NiwidXNlcklkIjoyfQ.3N0e83tTlN1hy5xn3aUbK0ZCKF2uvdreh3VP-UqCJls
